# frozen_string_literal: true

require_relative "instagram_publish_api_via_instagram_login/version"
require_relative "instagram_publish_api_via_instagram_login/authenticator"
require_relative "instagram_publish_api_via_instagram_login/user_details"
require_relative "instagram_publish_api_via_instagram_login/publisher"

module InstagramPublishApiViaInstagramLogin
  class Error < StandardError; end
end
